# -*- coding: utf-8 -*-
"""Distance_calculation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-QDz9LepyDcJHbrrQVbKIhw5fIdSNX4R
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

"""spatial proximity threshold setting
if the proximity between two user is below or less than the 2km means users are in contact.

FORMATING ABOVE ROWS AND COLUMNS INTO MATRIX FORMAT
"""

SP_df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Review_implementation/covid_data_from_Github/distance calc/distance_bihar.csv")

SP_df1

list1 = SP_df1.values.tolist()

list1

list1 = SP_df1.values.tolist()


count = 0

for list in list1:
   # print(count)
    for index in range(len(list)):
      if list[index] <= 1 and list[index] != 0:
       
        #print(index, ':', list[index])
        key = str(index)
        value = str(list[index])
        file1 = open("read2.txt", "a") 
        file1.write(str(count)) 
        file1.write(" ")
        file1.write(key)
        file1.write(" ")
        file1.write(value)
        file1.write("\n")
        
        
     
    #print("------")
    count = count+1



