# -*- coding: utf-8 -*-
"""Global_and_Self_Influence_(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thn6xRbWTPtrdQVcNGiEi_E_VrJZMf5a
"""

import networkx as nx
import matplotlib.pyplot as plt    #ploting the graph
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

G_df1=pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/data/kisslerPreprocessed.csv")

G_df1

G1=nx.from_pandas_edgelist(G_df1, 'source', 'target')

hist = nx.classes.function.degree_histogram(G1)
print(hist)

"""kshell algorithm

kshell values are copied into csv files.
"""

KshellVal_df = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/kshell.csv")

KshellVal_df

list1_df = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/nodelist.csv")

list1_df

list1 = list1_df['node'].tolist()

df1 = pd.DataFrame()

for source in list1:
       shortest_path= nx.single_source_dijkstra_path_length(G1,source,weight = '1')
       #dict_df = pd.DataFrame.from_dict(shortest_path)
       n_lis = [(value) for key, value in sorted(shortest_path.items())] 
       df1 = df1.append(pd.DataFrame([n_lis]))
       print(n_lis)

df1

vals = df1.values
print(vals)

# convert to list
print('---------------------')
print('Convert values to list')
vals.tolist()

"""#KSHell and dsistance influence of each node( ks/d)"""

KshellVal_df = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/kshell.csv")

KshellVal_df

k_shell_list = KshellVal_df['kshell'].tolist()



nodes_distances = vals.tolist()
GI = {}
count = 0;
#for k_shell in k_shell_list:
for nodes_distance in nodes_distances:
  sum = 0
  for index in range(len(nodes_distance)):
    if nodes_distance[index] == 0 :
      continue
    tmp =  k_shell_list[index]/nodes_distance[index] 
    sum = sum + tmp
    #print (nodes_distance[int(index)], sum, k_shell_list[int(index)]) 
  #GI = {count :   tmp + GI[count] }
  #GI[count] =  GI[count] + tmp
  GI[count] = sum
  print (GI[count])
  count = count + 1

import pandas as pd

(pd.DataFrame.from_dict(data=GI, orient='index')
   .to_csv('GI_centrality1.csv', header=True))

"""#Eigen Vector centrality of each node"""

centrality = nx.eigenvector_centrality(G1)
print(['%s %0.2f'%(node,centrality[node]) for node in centrality])

import pandas as pd

(pd.DataFrame.from_dict(data=centrality, orient='index')
   .to_csv('Eigen_vector_centrality1.csv', header=True))

"""#Global Influence calculation

(kshell(vi)/d(vij)) + EC(vi)
"""

GI_df = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/GI.csv")

GI_df

"""#Self Influence

degree centrality
"""

Degree_centrality_node = nx.degree_centrality(G1)
print(['%s %0.2f'%(node,Degree_centrality_node[node]) for node in Degree_centrality_node])

import pandas as pd

(pd.DataFrame.from_dict(data=Degree_centrality_node, orient='index')
   .to_csv('Degree_centrality.csv', header=True))

GI_df = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/Degree_centrality.csv")

GI_df

degree_cent = GI_df['influence'].tolist()

"""K shell values"""

KshellVal_df

"""#Self Influence"""

import math

k_shell_list = KshellVal_df['kshell'].tolist()

SI = {}
count = 0

for index in range(len(k_shell_list)):
  power_result = k_shell_list[index] * degree_cent[index]
  Final_result = math.sqrt(power_result)

  #print("Exponential Value is: ", )
  SI[count] = Final_result
  print (SI[count])
  count = count + 1

"""Final Influence"""

FinalInfluence_df =pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/output_file/Final_influence.csv")

FinalInfluence_df
