# -*- coding: utf-8 -*-
"""Haversine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197TzaupGVBwxPb0z5e6C-EUuvU19q2I5
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df1 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Review_implementation/covid_data_from_Github/Data_preprocessing/data_with_index.csv")

df1

pip install haversine

import math
import haversine as hs 
from haversine import haversine, Unit

"""Get radians"""

import math
df1['lat_rad'] = df1.latitude.apply(math.radians)
df1['long_rad'] = df1.longitude.apply(math.radians)

"""Calculate pairwise distances"""

from sklearn.metrics.pairwise import haversine_distances

for idx_from, from_point in df1.iterrows():
    for idx_to, to_point in df1.iterrows():
            column_name = f"Distance_to_point_{idx_from}"
            haversine_matrix = haversine_distances([[from_point.lat_rad, from_point.long_rad], [to_point.lat_rad, to_point.long_rad]])
            point_distance = haversine_matrix[0][1] * 6371000/1000  # multiply by Earth radius to get kilometers
            df1.loc[idx_to, column_name] = point_distance

df1.to_csv("MatrixForm_result.csv")