# -*- coding: utf-8 -*-
"""Kendall_CC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bALdMMnPH9TadvbYCu1L-T6-YXUD2GkY

## Example code
"""

from google.colab import drive
drive.mount('/content/drive')

"""read data from dataframe"""

import pandas as pd
df_SIR = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/SIR/SIR_AfterRank.csv")

df_alg = pd.read_csv("/content/drive/MyDrive/kissler/review_implementation/benchmarkalg/Benchmark_alg-20220324T044228Z-001/Benchmark_alg/myalg/myalgAfter_Rank.csv")

df_SIR

df_alg

"""converting dataframe to list"""

from scipy.stats import kendalltau
  
# Taking values from the above example in Lists
SIR1 = df_SIR['R1'].tolist()
SIR2 = df_SIR['R2'].tolist()
SIR3 = df_SIR['R3'].tolist()
SIR4 = df_SIR['R4'].tolist()
SIR5 = df_SIR['R5'].tolist()
SIR6 = df_SIR['R6'].tolist()
SIR7 = df_SIR['R7'].tolist()
SIR8 = df_SIR['R8'].tolist()
SIR9 = df_SIR['R9'].tolist()
SIR10 = df_SIR['R10'].tolist()
SIR11= df_SIR['R11'].tolist()
SIR12 = df_SIR['R12'].tolist()
SIR13 = df_SIR['R13'].tolist()
SIR14 = df_SIR['R14'].tolist()
SIR15 = df_SIR['R15'].tolist()





alg_res = df_alg['Rank'].tolist()



corr, _ = kendalltau(SIR1, alg_res)
print('iteration1: %.5f' % corr)

corr, _ = kendalltau(SIR2, alg_res)
print('iteration2: %.5f' % corr)


corr, _ = kendalltau(SIR3, alg_res)
print('iteration3: %.5f' % corr)

corr, _ = kendalltau(SIR4, alg_res)
print('iteration4: %.5f' % corr)

corr, _ = kendalltau(SIR5, alg_res)
print('iteration5: %.5f' % corr)

corr, _ = kendalltau(SIR6, alg_res)
print('iteration6: %.5f' % corr)

corr, _ = kendalltau(SIR7, alg_res)
print('iteration7: %.5f' % corr)

corr, _ = kendalltau(SIR8, alg_res)
print('iteration8: %.5f' % corr)

corr, _ = kendalltau(SIR9, alg_res)
print('iteration9: %.5f' % corr)
corr, _ = kendalltau(SIR10, alg_res)
print('iteration10: %.5f' % corr)
corr, _ = kendalltau(SIR11, alg_res)
print('iteration11: %.5f' % corr)
corr, _ = kendalltau(SIR12, alg_res)
print('iteration12: %.5f' % corr)
corr, _ = kendalltau(SIR13, alg_res)
print('iteration13: %.5f' % corr)
corr, _ = kendalltau(SIR14, alg_res)
print('iteration14: %.5f' % corr)
corr, _ = kendalltau(SIR15, alg_res)
print('iteration15: %.5f' % corr)

